<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType> 
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixBits.Core\PixBits.Core.csproj" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Nethereum.Web3" Version="5.0.0" />
  </ItemGroup>
</Project>